server:
  port: 12002
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    clean-disabled: false
